### ISSUE TITLE
slurm_job_handler.py depends on "hostlist" executable

### ISSUE THREAD

**Issue by cadejager** [lanl/Pavilion#27]
When I try to run on trinitite (and presumably other cray systems) with slurm I get the following error:

/bin/sh: hostlist: command not found
Traceback (most recent call last):
  File "/var/spool/slurm/job12009/slurm_script", line 156, in <module>
    sys.exit(main())
  File "/var/spool/slurm/job12009/slurm_script", line 101, in main
    nodes = get_node_list()
  File "/var/spool/slurm/job12009/slurm_script", line 85, in get_node_list
    output = subprocess.check_output("hostlist -e $SLURM_NODELIST", shell=True)
  File "/usr/lib64/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'hostlist -e $SLURM_NODELIST' returned non-zero exit status 127

**Comment by cadejager** [comment]
@BenCasses I have not fully tested this to make sure it is compatible but I will on Monday. I would appreciate someone else checking that this change still gets an equivalent output.
